
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 847594 bytes/channel
 *	Total Size: 1 * 847594 + 4 (header) = 847638 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/huda/Documents/School/Spring18/2261/Milestones/M03_HudaTauha/GameSong.wav
 *	Time-stamp: Thu Apr 12 22:52:15 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 847594

extern const unsigned char GameSong[847594];

#endif /* __GAMESONGH__ */
