
/**************************************************************
 *	
 *	ticking, 8 bit, 11025Hz,
 *	1 channel, 57888 bytes/channel
 *	Total Size: 1 * 57888 + 4 (header) = 57932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/huda/Documents/School/Spring18/2261/Milestones/M03_HudaTauha/ticking.wav
 *	Time-stamp: Thu Apr 12 22:41:13 2018
 *	
 **************************************************************/

#ifndef __TICKINGH__
#define __TICKINGH__

#define TICKINGFREQ 11025
#define TICKINGLEN 57888

extern const unsigned char ticking[57888];

#endif /* __TICKINGH__ */
