
/**************************************************************
 *	
 *	titleSong, 8 bit, 11025Hz,
 *	1 channel, 2051136 bytes/channel
 *	Total Size: 1 * 2051136 + 4 (header) = 2051180 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/huda/Documents/School/Spring18/2261/Milestones/M03_HudaTauha/titleSong.wav
 *	Time-stamp: Thu Apr 12 22:40:37 2018
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 2051136

extern const unsigned char titleSong[2051136];

#endif /* __TITLESONGH__ */
